### ISSUE TITLE
Try median on line 72?

### ISSUE THREAD

**Issue by pkrush** [FarmBot-Labs/measure-soil-height#1]
This code looks like a great start to me!

Stopping the camera to take a picture might be huge: sharper features, no rolling shutter effect, exact location.  It’s so nice to have the camera location. (Maybe I am a bit sensitive to this, I lost two weeks because of it.) 

Line 72: mean_disparity = np.mean(values): median or some combo of mean and median might be better.

**Comment by gabrielburnworth** [comment]
Thanks for the feedback! That part of the code has changed from what it was, but I'll keep median in mind for the future.
